# Make it possible to switch adapters by passing the ACTION_CABLE_ADAPTER env variable.
# For example, you can use it fallback to the standard Action Cable in staging/review
# environments (by setting `ACTION_CABLE_ADAPTER=redis`).
development:
  # adapter: redis
  # url: redis://127.0.0.1:6379
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7c8d2c37f43d5bf23f76c2d12136226f@crestfish.redistogo.com:9806/
